package amazingme.model;

import amazingme.util.Constants;

public enum Milestone {

    //TODO -> not all milestones are included, only those thought to be measurable in amazingme :: https://www.cdc.gov/ncbddd/actearly/milestones/milestones-2mo.html

    //2 month milestones
    BEGINS_TO_SMILE_AT_PEOPLE("", Constants.TWO_MONTHS, Constants.SIX_YEARS),
    CAN_BRIEFLY_CALM,HERSELF ("", Constants.TWO_MONTHS, Constants.SIX_YEARS),
    TRIES_TO_LOOK_AT_PARENT("", Constants.TWO_MONTHS, Constants.SIX_YEARS),
    COOS_OR_MAKES_GURGLING_SOUNDS("", Constants.TWO_MONTHS, Constants.SIX_YEARS),
    TURNS_HEAD_TOWARD_SOUNDS("", Constants.TWO_MONTHS, Constants.SIX_YEARS),
    PAYS_ATTENTION_TO_FACES("", Constants.TWO_MONTHS, Constants.SIX_YEARS),
    BEGINS_TO_FOLLOW_THINGS_WITH_EYES("", Constants.TWO_MONTHS, Constants.SIX_YEARS),
    CRIES_AND_FUSSES_IF_ACTIVITY_DOESNT_CHANGE("", Constants.TWO_MONTHS, Constants.SIX_YEARS),
    CAN_HOLD_HEAD_UP_AND_BEGINS_TO_PUSH_UP_WHEN_LYING_ON_TUMMY("", Constants.TWO_MONTHS, Constants.SIX_YEARS),
    MAKES_SMOOTHER_MOVEMENTS_WITH_ARMS_AND_LEGS("", Constants.TWO_MONTHS, Constants.SIX_YEARS),

    //4 month milestones
    SMILES_SPONTANEOUSLY_ESPECIALLY_AT_PEOPLE("", Constants.FOUR_MONTHS, Constants.SIX_YEARS),
    LIKES_TO_PLAY_WITH_PEOPLE_AND_MIGHT_CRY_WHEN_PLAYING_STOPS("", Constants.FOUR_MONTHS, Constants.SIX_YEARS),
    COPIES_SOME_MOVEMENTS_AND_FACIAL_EXPRESSIONS_LIKE_SMILING_OR_FROWNING("", Constants.FOUR_MONTHS, Constants.SIX_YEARS),
    BEGINS_TO_BABBLE("", Constants.FOUR_MONTHS, Constants.SIX_YEARS),
    BABBLES_WITH_EXPRESSION_AND_COPIES_SOUNDS_HE_HEARS("", Constants.FOUR_MONTHS, Constants.SIX_YEARS),
    CRIES_IN_DIFFERENT_WAYS_TO_SHOW_HUNGER_PAIN_OR_BEING_TIRED("", Constants.FOUR_MONTHS, Constants.SIX_YEARS),
    LETS_YOU_KNOW_IF_HE_IS_HAPPY_OR_SAD("", Constants.FOUR_MONTHS, Constants.SIX_YEARS),
    RESPONDS_TO_AFFECTION("", Constants.FOUR_MONTHS, Constants.SIX_YEARS),
    REACHES_FOR_TOY_WITH_ONE_HAND("", Constants.FOUR_MONTHS, Constants.SIX_YEARS),
    USES_HANDS_AND_EYES_TOGETHER_SUCH_AS_SEEING_A_TOY_AND_REACHING_FOR_IT("", Constants.FOUR_MONTHS, Constants.SIX_YEARS),
    FOLLOWS_MOVING_THINGS_WITH_EYES_FROM_SIDE_TO_SIDE("", Constants.FOUR_MONTHS, Constants.SIX_YEARS),
    WATCHES_FACES_CLOSELY("", Constants.FOUR_MONTHS, Constants.SIX_YEARS),
    RECOGNIZES_FAMILIAR_PEOPLE_AND_THINGS_AT_A_DISTANCE("", Constants.FOUR_MONTHS, Constants.SIX_YEARS),
    HOLDS_HEAD_STEADY_UNSUPPORTED("", Constants.FOUR_MONTHS, Constants.SIX_YEARS),
    PUSHES_DOWN_ON_LEGS_WHEN_FEET_ARE_ON_A_HARD_SURFACE("", Constants.FOUR_MONTHS, Constants.SIX_YEARS),
    MAY_BE_ABLE_TO_ROLL_OVER_FROM_TUMMY_TO_BACK("", Constants.FOUR_MONTHS, Constants.SIX_YEARS),
    CAN_HOLD_A_TOY_AND_SHAKE_IT_AND_SWING_AT_DANGLING_TOYS("", Constants.FOUR_MONTHS, Constants.SIX_YEARS),
    BRINGS_HANDS_TO_MOUTH("", Constants.FOUR_MONTHS, Constants.SIX_YEARS),
    WHEN_LYING_ON_STOMACH_PUSHES_UP_TO_ELBOWS("", Constants.FOUR_MONTHS, Constants.SIX_YEARS),

    //6 month milestones
    KNOWS_FAMILIAR_FACES_AND_BEGINS_TO_KNOW_IF_SOMEONE_IS_A_STRANGER("", Constants.SIX_MONTHS, Constants.SIX_YEARS),
    LIKES_TO_PLAY_WITH_OTHERS_ESPECIALLY_PARENTS("", Constants.SIX_MONTHS, Constants.SIX_YEARS),
    RESPONDS_TO_OTHER_PEOPLES_EMOTIONS_AND_OFTEN_SEEMS_HAPPY("", Constants.SIX_MONTHS, Constants.SIX_YEARS),
    LIKES_TO_LOOK_AT_SELF_IN_A_MIRROR("", Constants.SIX_MONTHS, Constants.SIX_YEARS),
    RESPONDS_TO_SOUNDS_BY_MAKING_SOUNDS("", Constants.SIX_MONTHS, Constants.SIX_YEARS),
    STRINGS_VOWELS_TOGETHER_WHEN_BABBLING_AH_EH_OH_AND_LIKES_TAKING_TURNS_WITH_PARENT_WHILE_MAKING_SOUNDS("", Constants.SIX_MONTHS, Constants.SIX_YEARS),
    RESPONDS_TO_OWN_NAME("", Constants.SIX_MONTHS, Constants.SIX_YEARS),
    MAKES_SOUNDS_TO_SHOW_JOY_AND_DISPLEASURE("", Constants.SIX_MONTHS, Constants.SIX_YEARS),
    BEGINS_TO_SAY_CONSONANT_SOUNDS_JABBERING_WITH_M_B("", Constants.SIX_MONTHS, Constants.SIX_YEARS),
    LOOKS_AROUND_AT_THINGS_NEARBY("", Constants.SIX_MONTHS, Constants.SIX_YEARS),
    BRINGS_THINGS_TO_MOUTH("", Constants.SIX_MONTHS, Constants.SIX_YEARS),
    SHOWS_CURIOSITY_ABOUT_THINGS_AND_TRIES_TO_GET_THINGS_THAT_ARE_OUT_OF_REACH("", Constants.SIX_MONTHS, Constants.SIX_YEARS),
    BEGINS_TO_PASS_THINGS_FROM_ONE_HAND_TO_THE_OTHER("", Constants.SIX_MONTHS, Constants.SIX_YEARS),
    ROLLS_OVER_IN_BOTH_DIRECTIONS_FRONT_TO_BACK_BACK_TO_FRONT("", Constants.SIX_MONTHS, Constants.SIX_YEARS),
    BEGINS_TO_SIT_WITHOUT_SUPPORT("", Constants.SIX_MONTHS, Constants.SIX_YEARS),
    WHEN_STANDING_SUPPORTS_WEIGHT_ON_LEGS_AND_MIGHT_BOUNCE("", Constants.SIX_MONTHS, Constants.SIX_YEARS),
    ROCKS_BACK_AND_FORTH_SOMETIMES_CRAWLING_BACKWARD_BEFORE_MOVING_FORWARD("", Constants.SIX_MONTHS, Constants.SIX_YEARS),

    //9 month milestones
    MAY_BE_AFRAID_OF_STRANGERS("", Constants.NINE_MONTHS, Constants.SIX_YEARS),
    MAY_BE_CLINGY_WITH_FAMILIAR_ADULTS("", Constants.NINE_MONTHS, Constants.SIX_YEARS),
    HAS_FAVORITE_TOYS("", Constants.NINE_MONTHS, Constants.SIX_YEARS),
    UNDERSTANDS_NO("", Constants.NINE_MONTHS, Constants.SIX_YEARS),
    MAKES_A_LOT_OF_DIFFERENT_SOUNDS_LIKE_MAMAMAMA_AND_BABABABABA("", Constants.NINE_MONTHS, Constants.SIX_YEARS),
    COPIES_SOUNDS_AND_GESTURES_OF_OTHERS("", Constants.NINE_MONTHS, Constants.SIX_YEARS),
    USES_FINGERS_TO_POINT_AT_THINGS("", Constants.NINE_MONTHS, Constants.SIX_YEARS),
    WATCHES_THE_PATH_OF_SOMETHING_AS_IT_FALLS("", Constants.NINE_MONTHS, Constants.SIX_YEARS),
    LOOKS_FOR_THINGS_SHE_SEES_YOU_HIDE("", Constants.NINE_MONTHS, Constants.SIX_YEARS),
    PLAYS_PEEK_A_BOO("", Constants.NINE_MONTHS, Constants.SIX_YEARS),
    PUTS_THINGS_IN_HIS_MOUTH("", Constants.NINE_MONTHS, Constants.SIX_YEARS),
    MOVES_THINGS_SMOOTHLY_FROM_ONE_HAND_TO_THE_OTHER("", Constants.NINE_MONTHS, Constants.SIX_YEARS),
    PICKS_UP_THINGS_LIKE_CEREAL_OS_BETWEEN_THUMB_AND_INDEX_FINGER("", Constants.NINE_MONTHS, Constants.SIX_YEARS),
    STANDS_HOLDING_ON("", Constants.NINE_MONTHS, Constants.SIX_YEARS),
    CAN_GET_INTO_SITTING_POSITION("", Constants.NINE_MONTHS, Constants.SIX_YEARS),
    SITS_WITHOUT_SUPPORT("", Constants.NINE_MONTHS, Constants.SIX_YEARS),
    PULLS_TO_STAND("", Constants.NINE_MONTHS, Constants.SIX_YEARS),
    CRAWLS("", Constants.NINE_MONTHS, Constants.SIX_YEARS),


    UNDERSTANDS_WORDS_LIKE_IN_ON_OR_UNDER("", Constants.THREE_YEARS, Constants.SIX_YEARS);

    int appropriateAgeMinimum;
    int appropriateAgeMaximum;
    String descriptor;

    Milestone(String description, int minAge, int maxAge) {
        this.descriptor = description;
        this.appropriateAgeMinimum = minAge;
        this.appropriateAgeMaximum = maxAge;
    }

    Milestone() {
        this("no description available", 0, 0);
    }

}
