package amazingme.model;

import amazingme.util.Constants;

public enum Milestone {

    //TODO -> not all milestones are included, only those thought to be measurable in amazingme :: https://www.cdc.gov/ncbddd/actearly/milestones/milestones-2mo.html

    // for default constructors and cases
    NONE,

    //2 month milestones
    BEGINS_TO_SMILE_AT_PEOPLE("", Constants.TWO_MONTHS, Constants.SIX_YEARS),
    CAN_BRIEFLY_CALM,HERSELF ("", Constants.TWO_MONTHS, Constants.SIX_YEARS),
    TRIES_TO_LOOK_AT_PARENT("", Constants.TWO_MONTHS, Constants.SIX_YEARS),

    COOS_OR_MAKES_GURGLING_SOUNDS("", Constants.TWO_MONTHS, Constants.SIX_YEARS),
    TURNS_HEAD_TOWARD_SOUNDS("", Constants.TWO_MONTHS, Constants.SIX_YEARS),

    PAYS_ATTENTION_TO_FACES("", Constants.TWO_MONTHS, Constants.SIX_YEARS),
    BEGINS_TO_FOLLOW_THINGS_WITH_EYES("", Constants.TWO_MONTHS, Constants.SIX_YEARS),
    CRIES_AND_FUSSES_IF_ACTIVITY_DOESNT_CHANGE("", Constants.TWO_MONTHS, Constants.SIX_YEARS),

    CAN_HOLD_HEAD_UP_AND_BEGINS_TO_PUSH_UP_WHEN_LYING_ON_TUMMY("", Constants.TWO_MONTHS, Constants.SIX_YEARS),
    MAKES_SMOOTHER_MOVEMENTS_WITH_ARMS_AND_LEGS("", Constants.TWO_MONTHS, Constants.SIX_YEARS),

    //4 month milestones
    SMILES_SPONTANEOUSLY_ESPECIALLY_AT_PEOPLE("", Constants.FOUR_MONTHS, Constants.SIX_YEARS),
    LIKES_TO_PLAY_WITH_PEOPLE_AND_MIGHT_CRY_WHEN_PLAYING_STOPS("", Constants.FOUR_MONTHS, Constants.SIX_YEARS),
    COPIES_SOME_MOVEMENTS_AND_FACIAL_EXPRESSIONS_LIKE_SMILING_OR_FROWNING("", Constants.FOUR_MONTHS, Constants.SIX_YEARS),

    BEGINS_TO_BABBLE("", Constants.FOUR_MONTHS, Constants.SIX_YEARS),
    BABBLES_WITH_EXPRESSION_AND_COPIES_SOUNDS_HE_HEARS("", Constants.FOUR_MONTHS, Constants.SIX_YEARS),
    CRIES_IN_DIFFERENT_WAYS_TO_SHOW_HUNGER_PAIN_OR_BEING_TIRED("", Constants.FOUR_MONTHS, Constants.SIX_YEARS),

    LETS_YOU_KNOW_IF_HE_IS_HAPPY_OR_SAD("", Constants.FOUR_MONTHS, Constants.SIX_YEARS),
    RESPONDS_TO_AFFECTION("", Constants.FOUR_MONTHS, Constants.SIX_YEARS),
    REACHES_FOR_TOY_WITH_ONE_HAND("", Constants.FOUR_MONTHS, Constants.SIX_YEARS),
    USES_HANDS_AND_EYES_TOGETHER_SUCH_AS_SEEING_A_TOY_AND_REACHING_FOR_IT("", Constants.FOUR_MONTHS, Constants.SIX_YEARS),
    FOLLOWS_MOVING_THINGS_WITH_EYES_FROM_SIDE_TO_SIDE("", Constants.FOUR_MONTHS, Constants.SIX_YEARS),
    WATCHES_FACES_CLOSELY("", Constants.FOUR_MONTHS, Constants.SIX_YEARS),
    RECOGNIZES_FAMILIAR_PEOPLE_AND_THINGS_AT_A_DISTANCE("", Constants.FOUR_MONTHS, Constants.SIX_YEARS),

    HOLDS_HEAD_STEADY_UNSUPPORTED("", Constants.FOUR_MONTHS, Constants.SIX_YEARS),
    PUSHES_DOWN_ON_LEGS_WHEN_FEET_ARE_ON_A_HARD_SURFACE("", Constants.FOUR_MONTHS, Constants.SIX_YEARS),
    MAY_BE_ABLE_TO_ROLL_OVER_FROM_TUMMY_TO_BACK("", Constants.FOUR_MONTHS, Constants.SIX_YEARS),
    CAN_HOLD_A_TOY_AND_SHAKE_IT_AND_SWING_AT_DANGLING_TOYS("", Constants.FOUR_MONTHS, Constants.SIX_YEARS),
    BRINGS_HANDS_TO_MOUTH("", Constants.FOUR_MONTHS, Constants.SIX_YEARS),
    WHEN_LYING_ON_STOMACH_PUSHES_UP_TO_ELBOWS("", Constants.FOUR_MONTHS, Constants.SIX_YEARS),

    //6 month milestones
    KNOWS_FAMILIAR_FACES_AND_BEGINS_TO_KNOW_IF_SOMEONE_IS_A_STRANGER("", Constants.SIX_MONTHS, Constants.SIX_YEARS),
    LIKES_TO_PLAY_WITH_OTHERS_ESPECIALLY_PARENTS("", Constants.SIX_MONTHS, Constants.SIX_YEARS),
    RESPONDS_TO_OTHER_PEOPLES_EMOTIONS_AND_OFTEN_SEEMS_HAPPY("", Constants.SIX_MONTHS, Constants.SIX_YEARS),
    LIKES_TO_LOOK_AT_SELF_IN_A_MIRROR("", Constants.SIX_MONTHS, Constants.SIX_YEARS),

    RESPONDS_TO_SOUNDS_BY_MAKING_SOUNDS("", Constants.SIX_MONTHS, Constants.SIX_YEARS),
    STRINGS_VOWELS_TOGETHER_WHEN_BABBLING_AH_EH_OH_AND_LIKES_TAKING_TURNS_WITH_PARENT_WHILE_MAKING_SOUNDS("", Constants.SIX_MONTHS, Constants.SIX_YEARS),
    RESPONDS_TO_OWN_NAME("", Constants.SIX_MONTHS, Constants.SIX_YEARS),
    MAKES_SOUNDS_TO_SHOW_JOY_AND_DISPLEASURE("", Constants.SIX_MONTHS, Constants.SIX_YEARS),
    BEGINS_TO_SAY_CONSONANT_SOUNDS_JABBERING_WITH_M_B("", Constants.SIX_MONTHS, Constants.SIX_YEARS),

    LOOKS_AROUND_AT_THINGS_NEARBY("", Constants.SIX_MONTHS, Constants.SIX_YEARS),
    BRINGS_THINGS_TO_MOUTH("", Constants.SIX_MONTHS, Constants.SIX_YEARS),
    SHOWS_CURIOSITY_ABOUT_THINGS_AND_TRIES_TO_GET_THINGS_THAT_ARE_OUT_OF_REACH("", Constants.SIX_MONTHS, Constants.SIX_YEARS),
    BEGINS_TO_PASS_THINGS_FROM_ONE_HAND_TO_THE_OTHER("", Constants.SIX_MONTHS, Constants.SIX_YEARS),

    ROLLS_OVER_IN_BOTH_DIRECTIONS_FRONT_TO_BACK_BACK_TO_FRONT("", Constants.SIX_MONTHS, Constants.SIX_YEARS),
    BEGINS_TO_SIT_WITHOUT_SUPPORT("", Constants.SIX_MONTHS, Constants.SIX_YEARS),
    WHEN_STANDING_SUPPORTS_WEIGHT_ON_LEGS_AND_MIGHT_BOUNCE("", Constants.SIX_MONTHS, Constants.SIX_YEARS),
    ROCKS_BACK_AND_FORTH_SOMETIMES_CRAWLING_BACKWARD_BEFORE_MOVING_FORWARD("", Constants.SIX_MONTHS, Constants.SIX_YEARS),

    //9 month milestones
    MAY_BE_AFRAID_OF_STRANGERS("", Constants.NINE_MONTHS, Constants.SIX_YEARS),
    MAY_BE_CLINGY_WITH_FAMILIAR_ADULTS("", Constants.NINE_MONTHS, Constants.SIX_YEARS),
    HAS_FAVORITE_TOYS("", Constants.NINE_MONTHS, Constants.SIX_YEARS),

    UNDERSTANDS_NO("", Constants.NINE_MONTHS, Constants.SIX_YEARS),
    MAKES_A_LOT_OF_DIFFERENT_SOUNDS_LIKE_MAMAMAMA_AND_BABABABABA("", Constants.NINE_MONTHS, Constants.SIX_YEARS),
    COPIES_SOUNDS_AND_GESTURES_OF_OTHERS("", Constants.NINE_MONTHS, Constants.SIX_YEARS),
    USES_FINGERS_TO_POINT_AT_THINGS("", Constants.NINE_MONTHS, Constants.SIX_YEARS),

    WATCHES_THE_PATH_OF_SOMETHING_AS_IT_FALLS("", Constants.NINE_MONTHS, Constants.SIX_YEARS),
    LOOKS_FOR_THINGS_SHE_SEES_YOU_HIDE("", Constants.NINE_MONTHS, Constants.SIX_YEARS),
    PLAYS_PEEK_A_BOO("", Constants.NINE_MONTHS, Constants.SIX_YEARS),
    PUTS_THINGS_IN_HIS_MOUTH("", Constants.NINE_MONTHS, Constants.SIX_YEARS),
    MOVES_THINGS_SMOOTHLY_FROM_ONE_HAND_TO_THE_OTHER("", Constants.NINE_MONTHS, Constants.SIX_YEARS),
    PICKS_UP_THINGS_LIKE_CEREAL_OS_BETWEEN_THUMB_AND_INDEX_FINGER("", Constants.NINE_MONTHS, Constants.SIX_YEARS),

    STANDS_HOLDING_ON("", Constants.NINE_MONTHS, Constants.SIX_YEARS),
    CAN_GET_INTO_SITTING_POSITION("", Constants.NINE_MONTHS, Constants.SIX_YEARS),
    SITS_WITHOUT_SUPPORT("", Constants.NINE_MONTHS, Constants.SIX_YEARS),
    PULLS_TO_STAND("", Constants.NINE_MONTHS, Constants.SIX_YEARS),
    CRAWLS("", Constants.NINE_MONTHS, Constants.SIX_YEARS),

    //1 year milestones
    IS_SHY_OR_NERVOUS_WITH_STRANGERS("", Constants.ONE_YEAR, Constants.SIX_YEARS),
    CRIES_WHEN_MOM_OR_DAD_LEAVES("", Constants.ONE_YEAR, Constants.SIX_YEARS),
    HAS_FAVORITE_THINGS_AND_PEOPLE("", Constants.ONE_YEAR, Constants.SIX_YEARS),
    SHOWS_FEAR_IN_SOME_SITUATIONS("", Constants.ONE_YEAR, Constants.SIX_YEARS),
    HANDS_YOU_A_BOOK_WHEN_HE_WANTS_TO_HEAR_A_STORY("", Constants.ONE_YEAR, Constants.SIX_YEARS),
    REPEATS_SOUNDS_OR_ACTIONS_TO_GET_ATTENTION("", Constants.ONE_YEAR, Constants.SIX_YEARS),
    PUTS_OUT_ARM_OR_LEG_TO_HELP_WITH_DRESSING("", Constants.ONE_YEAR, Constants.SIX_YEARS),
    PLAYS_GAMES_SUCH_AS_PEEK_A_BOO_AND_PAT_A_CAKE("", Constants.ONE_YEAR, Constants.SIX_YEARS),

    RESPONDS_TO_SIMPLE_SPOKEN_REQUESTS("", Constants.ONE_YEAR, Constants.SIX_YEARS),
    USES_SIMPLE_GESTURES_LIKE_SHAKING_HEAD_NO_OR_WAVING_BYE_BYE("", Constants.ONE_YEAR, Constants.SIX_YEARS),
    MAKES_SOUNDS_WITH_CHANGES_IN_TONE_SOUNDS_MORE_LIKE_SPEECH("", Constants.ONE_YEAR, Constants.SIX_YEARS),
    SAYS_MAMA_AND_DADA_AND_EXCLAMATIONS_LIKE_UH_OH("", Constants.ONE_YEAR, Constants.SIX_YEARS),
    TRIES_TO_SAY_WORDS_YOU_SAY("", Constants.ONE_YEAR, Constants.SIX_YEARS),

    EXPLORES_THINGS_IN_DIFFERENT_WAYS_LIKE_SHAKING_BANGING_THROWING("", Constants.ONE_YEAR, Constants.SIX_YEARS),
    FINDS_HIDDEN_THINGS_EASILY("", Constants.ONE_YEAR, Constants.SIX_YEARS),
    LOOKS_AT_THE_RIGHT_PICTURES_OR_THING_WHEN_ITS_NAMED("", Constants.ONE_YEAR, Constants.SIX_YEARS),
    COPIES_GESTURES("", Constants.ONE_YEAR, Constants.SIX_YEARS),
    STARTS_TO_USE_THINGS_CORRECTLY_FOR_EXAMPLE_DRINKS_FROM_A_CUP_BRUSHES_HAIR("", Constants.ONE_YEAR, Constants.SIX_YEARS),
    BANGS_TWO_THINGS_TOGETHER("", Constants.ONE_YEAR, Constants.SIX_YEARS),
    PUTS_THINGS_IN_A_CONTAINER_TAKES_THINGS_OUT_OF_A_CONTAINER("", Constants.ONE_YEAR, Constants.SIX_YEARS),
    LETS_THINGS_GO_WITHOUT_HELP("", Constants.ONE_YEAR, Constants.SIX_YEARS),
    POKES_WITH_INDEX_FINGER("", Constants.ONE_YEAR, Constants.SIX_YEARS),
    FOLLOWS_SIMPLE_DIRECTIONS_LIKE_PICK_UP_THE_TOY("", Constants.ONE_YEAR, Constants.SIX_YEARS),

    GETS_TO_A_SITTING_POSITION_WITHOUT_HELP("", Constants.ONE_YEAR, Constants.SIX_YEARS),
    PULLS_UP_TO_STAND_WALKS_HOLDING_ON_TO_FURNITURE("", Constants.ONE_YEAR, Constants.SIX_YEARS),
    MAY_TAKE_A_FEW_STEPS_WITHOUT_HOLDING_ON("", Constants.ONE_YEAR, Constants.SIX_YEARS),
    MAY_STAND_ALONE("", Constants.ONE_YEAR, Constants.SIX_YEARS),

    //18 Month Milestone
    LIKES_TO_HAND_THINGS_TO_OTHERS_AS_PLAY("", Constants.EIGHTEEN_MONTHS, Constants.SIX_YEARS),
    MAY_HAVE_TEMPER_TANTRUMS("", Constants.EIGHTEEN_MONTHS, Constants.SIX_YEARS),
    MAY_BE_AFRAID_OF_STRANGERS_TWO("", Constants.EIGHTEEN_MONTHS, Constants.SIX_YEARS),
    SHOWS_AFFECTION_TO_FAMILIAR_PEOPLE("", Constants.EIGHTEEN_MONTHS, Constants.SIX_YEARS),
    PLAYS_SIMPLE_PRETEND_SUCH_AS_FEEDING_A_DOLL("", Constants.EIGHTEEN_MONTHS, Constants.SIX_YEARS),
    MAY_CLING_TO_CAREGIVERS_IN_NEW_SITUATIONS("", Constants.EIGHTEEN_MONTHS, Constants.SIX_YEARS),
    POINTS_TO_SHOW_OTHERS_SOMETHING_INTERESTING("", Constants.EIGHTEEN_MONTHS, Constants.SIX_YEARS),
    EXPLORES_ALONE_BUT_WITH_PARENT_CLOSE_BY("", Constants.EIGHTEEN_MONTHS, Constants.SIX_YEARS),

    SAYS_SEVERAL_SINGLE_WORDS("", Constants.EIGHTEEN_MONTHS, Constants.SIX_YEARS),
    SAYS_AND_SHAKES_HEAD_NO("", Constants.EIGHTEEN_MONTHS, Constants.SIX_YEARS),
    POINTS_TO_SHOW_SOMEONE_WHAT_HE_WANTS("", Constants.EIGHTEEN_MONTHS, Constants.SIX_YEARS),

    KNOWS_WHAT_ORDINARY_THINGS_ARE_FOR_FOR_EXAMPLE_TELEPHONE_BRUSH_SPOON("", Constants.EIGHTEEN_MONTHS, Constants.SIX_YEARS),
    POINTS_TO_GET_THE_ATTENTION_OF_OTHERS("", Constants.EIGHTEEN_MONTHS, Constants.SIX_YEARS),
    SHOWS_INTEREST_IN_A_DOLL_OR_STUFFED_ANIMAL_BY_PRETENDING_TO_FEED("", Constants.EIGHTEEN_MONTHS, Constants.SIX_YEARS),
    POINTS_TO_ONE_BODY_PART("", Constants.EIGHTEEN_MONTHS, Constants.SIX_YEARS),
    SCRIBBLES_ON_HIS_OWN("", Constants.EIGHTEEN_MONTHS, Constants.SIX_YEARS),
    CAN_FOLLOW_ONE_STEP_VERBAL_COMMANDS_WITHOUT_ANY_GESTURES_FOR_EXAMPLE_SITS_WHEN_YOU_SAY_SIT_DOWN("", Constants.EIGHTEEN_MONTHS, Constants.SIX_YEARS),

    WALKS_ALONE("", Constants.EIGHTEEN_MONTHS, Constants.SIX_YEARS),
    MAY_WALK_UP_STEPS_AND_RUN("", Constants.EIGHTEEN_MONTHS, Constants.SIX_YEARS),
    PULLS_TOYS_WHILE_WALKING("", Constants.EIGHTEEN_MONTHS, Constants.SIX_YEARS),
    CAN_HELP_UNDRESS_HERSELF("", Constants.EIGHTEEN_MONTHS, Constants.SIX_YEARS),
    DRINKS_FROM_A_CUP("", Constants.EIGHTEEN_MONTHS, Constants.SIX_YEARS),
    EATS_WITH_A_SPOON("", Constants.EIGHTEEN_MONTHS, Constants.SIX_YEARS),

    //2 Year Milestones
    COPIES_OTHERS_ESPECIALLY_ADULTS_AND_OLDER_CHILDREN("", Constants.TWO_YEARS, Constants.SIX_YEARS),
    GETS_EXCITED_WHEN_WITH_OTHER_CHILDREN("", Constants.TWO_YEARS, Constants.SIX_YEARS),
    SHOWS_MORE_AND_MORE_INDEPENDENCE("", Constants.TWO_YEARS, Constants.SIX_YEARS),
    SHOWS_DEFIANT_BEHAVIOR_DOING_WHAT_HE_HAS_BEEN_TOLD_NOT_TO("", Constants.TWO_YEARS, Constants.SIX_YEARS),
    PLAYS_MAINLY_BESIDE_OTHER_CHILDREN_BUT_IS_BEGINNING_TO_INCLUDE_OTHER_CHILDREN_SUCH_AS_IN_CHASE_GAMES("", Constants.TWO_YEARS, Constants.SIX_YEARS),

    POINTS_TO_THINGS_OR_PICTURES_WHEN_THEY_ARE_NAMED("", Constants.TWO_YEARS, Constants.SIX_YEARS),
    KNOWS_NAMES_OF_FAMILIAR_PEOPLE_AND_BODY_PARTS("", Constants.TWO_YEARS, Constants.SIX_YEARS),
    SAYS_SENTENCES_WITH_TWO_TO_FOUR_WORDS("", Constants.TWO_YEARS, Constants.SIX_YEARS),
    FOLLOWS_SIMPLE_INSTRUCTIONS("", Constants.TWO_YEARS, Constants.SIX_YEARS),
    REPEATS_WORDS_OVERHEARD_IN_CONVERSATION("", Constants.TWO_YEARS, Constants.SIX_YEARS),
    POINTS_TO_THINGS_IN_A_BOOK("", Constants.TWO_YEARS, Constants.SIX_YEARS),

    FINDS_THINGS_EVEN_WHEN_HIDDEN_UNDER_TWO_OR_THREE_COVERS("", Constants.TWO_YEARS, Constants.SIX_YEARS),
    BEGINS_TO_SORT_SHAPES_AND_COLORS("", Constants.TWO_YEARS, Constants.SIX_YEARS),
    COMPLETES_SENTENCES_AND_RHYMES_IN_FAMILIAR_BOOKS("", Constants.TWO_YEARS, Constants.SIX_YEARS),
    PLAYS_SIMPLE_MAKE_BELIEVE_GAMES("", Constants.TWO_YEARS, Constants.SIX_YEARS),
    BUILDS_TOWERS_OF_FOUR_OR_MORE_BLOCKS("", Constants.TWO_YEARS, Constants.SIX_YEARS),
    MIGHT_USE_ONE_HAND_MORE_THAN_THE_OTHER("", Constants.TWO_YEARS, Constants.SIX_YEARS),
    FOLLOWS_TWO_STEP_INSTRUCTIONS_SUCH_AS_PICK_UP_YOUR_SHOES_AND_PUT_THEM_IN_THE_CLOSET("", Constants.TWO_YEARS, Constants.SIX_YEARS),
    NAMES_ITEMS_IN_A_PICTURE_BOOK_SUCH_AS_A_CAT_BIRD_OR_DOG("", Constants.TWO_YEARS, Constants.SIX_YEARS),

    STANDS_ON_TIPTOE("", Constants.TWO_YEARS, Constants.SIX_YEARS),
    KICKS_A_BALL("", Constants.TWO_YEARS, Constants.SIX_YEARS),
    BEGINS_TO_RUN("", Constants.TWO_YEARS, Constants.SIX_YEARS),
    CLIMBS_ONTO_AND_DOWN_FROM_FURNITURE_WITHOUT_HELP("", Constants.TWO_YEARS, Constants.SIX_YEARS),
    WALKS_UP_AND_DOWN_STAIRS_HOLDING_ON("", Constants.TWO_YEARS, Constants.SIX_YEARS),
    THROWS_BALL_OVERHEAD("", Constants.TWO_YEARS, Constants.SIX_YEARS),
    MAKES_OR_COPIES_STRAIGHT_LINES_AND_CIRCLES("", Constants.TWO_YEARS, Constants.SIX_YEARS),

    //3 Year Milestones
    COPIES_ADULTS_AND_FRIENDS("", Constants.THREE_YEARS, Constants.SIX_YEARS),
    SHOWS_AFFECTION_FOR_FRIENDS_WITHOUT_PROMPTING("", Constants.THREE_YEARS, Constants.SIX_YEARS),
    TAKES_TURNS_IN_GAMES("", Constants.THREE_YEARS, Constants.SIX_YEARS),
    SHOWS_CONCERN_FOR_CRYING_FRIEND("", Constants.THREE_YEARS, Constants.SIX_YEARS),
    UNDERSTANDS_THE_IDEA_OF_MINE_AND_HIS_OR_HERS("", Constants.THREE_YEARS, Constants.SIX_YEARS),
    SHOWS_WIDE_RANGE_OF_EMOTIONS("", Constants.THREE_YEARS, Constants.SIX_YEARS),
    SEPARATES_EASILY_FROM_MOM_AND_DAD("", Constants.THREE_YEARS, Constants.SIX_YEARS),
    MAY_GET_UPSET_WITH_MAJOR_CHANGES_IN_ROUTINE("", Constants.THREE_YEARS, Constants.SIX_YEARS),
    DRESSES_AND_UNDRESSES_SELF("", Constants.THREE_YEARS, Constants.SIX_YEARS),

    FOLLOWS_INSTRUCTIONS_WITH_TWO_OR_THREE_STEPS("", Constants.THREE_YEARS, Constants.SIX_YEARS),
    CAN_NAME_MOST_FAMILIAR_THINGS("", Constants.THREE_YEARS, Constants.SIX_YEARS),
    UNDERSTANDS_WORDS_LIKE_IN_ON_AND_UNDER("", Constants.THREE_YEARS, Constants.SIX_YEARS),
    SAYS_FIRST_NAME_AGE_AND_SEX("", Constants.THREE_YEARS, Constants.SIX_YEARS),
    NAMES_A_FRIEND("", Constants.THREE_YEARS, Constants.SIX_YEARS),
    SAYS_WORDS_LIKE_I_ME_WE_AND_YOU_AND_SOME_PLURALS_CARS_DOGS_CATS("", Constants.THREE_YEARS, Constants.SIX_YEARS),
    TALKS_WELL_ENOUGH_FOR_STRANGERS_TO_UNDERSTAND_MOST_OF_THE_TIME("", Constants.THREE_YEARS, Constants.SIX_YEARS),
    CARRIES_ON_A_CONVERSATION_USING_TWO_TO_THREE_SENTENCES("", Constants.THREE_YEARS, Constants.SIX_YEARS),

    CAN_WORK_TOYS_WITH_BUTTONS_LEVERS_AND_MOVING_PARTS("", Constants.THREE_YEARS, Constants.SIX_YEARS),
    PLAYS_MAKE_BELIEVE_WITH_DOLLS_ANIMALS_AND_PEOPLE("", Constants.THREE_YEARS, Constants.SIX_YEARS),
    DOES_PUZZLES_WITH_THREE_OR_FOUR_PIECES("", Constants.THREE_YEARS, Constants.SIX_YEARS),
    UNDERSTANDS_WHAT_TWO_MEANS("", Constants.THREE_YEARS, Constants.SIX_YEARS),
    COPIES_A_CIRCLE_WITH_PENCIL_OR_CRAYON("", Constants.THREE_YEARS, Constants.SIX_YEARS),
    TURNS_BOOK_PAGES_ONE_AT_A_TIME("", Constants.THREE_YEARS, Constants.SIX_YEARS),
    BUILDS_TOWERS_OF_MORE_THAN_SIX_BLOCKS("", Constants.THREE_YEARS, Constants.SIX_YEARS),
    SCREWS_AND_UNSCREWS_JAR_LIDS_OR_TURNS_DOOR_HANDLE("", Constants.THREE_YEARS, Constants.SIX_YEARS),

    CLIMBS_WELL("", Constants.THREE_YEARS, Constants.SIX_YEARS),
    RUNS_EASILY("", Constants.THREE_YEARS, Constants.SIX_YEARS),
    PEDALS_A_TRICYLCE_THREE_WHEEL_BIKE("", Constants.THREE_YEARS, Constants.SIX_YEARS),
    WALKS_UP_AND_DOWN_STAIRS_ONE_FOOT_ON_EACH_STEP("", Constants.THREE_YEARS, Constants.SIX_YEARS),

    //4 Year Milestones
    ENJOYS_DOING_NEW_THINGS("", Constants.FOUR_YEARS, Constants.SIX_YEARS),
    PLAYS_MOM_AND_DAD("", Constants.FOUR_YEARS, Constants.SIX_YEARS),
    IS_MORE_AND_MORE_CREATIVE_WITH_MAKE_BELIEVE_PLAY("", Constants.FOUR_YEARS, Constants.SIX_YEARS),
    WOULD_RATHER_PLAY_WITH_OTHER_CHILDREN_THAN_BY_HIMSELF("", Constants.FOUR_YEARS, Constants.SIX_YEARS),
    COOPERATES_WITH_OTHER_CHILDREN("", Constants.FOUR_YEARS, Constants.SIX_YEARS),
    OFTEN_CANT_TELL_WHATS_REAL_AND_WHATS_MAKE_BELIEVE("", Constants.FOUR_YEARS, Constants.SIX_YEARS),
    TALKS_ABOUT_WHAT_SHE_LIKES_AND_WHAT_SHE_IS_INTERESTED_IN("", Constants.FOUR_YEARS, Constants.SIX_YEARS),

    KNOWS_SOME_BASIC_RULES_OF_GRAMMAR_SUCH_AS_CORRECTLY_USING_HE_AND_SHE("", Constants.FOUR_YEARS, Constants.SIX_YEARS),
    SINGS_A_SONG_OR_SAYS_A_POEM_FROM_MEMORY_SUCH_AS_THE_ITSY_BITSY_SPIDER_OR_THE_WHEELS_ON_THE_BUS("", Constants.FOUR_YEARS, Constants.SIX_YEARS),
    TELLS_STORIES("", Constants.FOUR_YEARS, Constants.SIX_YEARS),
    CAN_SAY_FIRST_AND_LAST_NAME("", Constants.FOUR_YEARS, Constants.SIX_YEARS),

    NAMES_SOME_COLORS_AND_SOME_NUMBERS("", Constants.FOUR_YEARS, Constants.SIX_YEARS),
    UNDERSTANDS_THE_IDEA_OF_COUNTING("", Constants.FOUR_YEARS, Constants.SIX_YEARS),
    STARTS_TO_UNDERSTANT_TIME("", Constants.FOUR_YEARS, Constants.SIX_YEARS),
    REMEMBERS_PARTS_OF_A_STORY("", Constants.FOUR_YEARS, Constants.SIX_YEARS),
    UNDERSTANDS_THE_IDEA_OF_SAME_AND_DIFFERENT("", Constants.FOUR_YEARS, Constants.SIX_YEARS),
    DRAWS_A_PERSON_WITH_TWO_TO_FOUR_BODY_PARTS("", Constants.FOUR_YEARS, Constants.SIX_YEARS),
    USES_SCISSORS("", Constants.FOUR_YEARS, Constants.SIX_YEARS),
    STARTS_TO_COPY_SOME_CAPITAL_LETTERS("", Constants.FOUR_YEARS, Constants.SIX_YEARS),
    PLAYS_BOARD_OR_CARD_GAMES("", Constants.FOUR_YEARS, Constants.SIX_YEARS),
    TELLS_YOU_WHAT_HE_THINKS_IS_GOING_TO_HAPPEN_NEXT_IN_A_BOOK("", Constants.FOUR_YEARS, Constants.SIX_YEARS),

    HOPS_AND_STANDS_ON_ONE_FOOT_UP_TO_TWO_SECONDS("", Constants.FOUR_YEARS, Constants.SIX_YEARS),
    CATCHES_A_BOUNCED_BALL_MOST_OF_THE_TIME("", Constants.FOUR_YEARS, Constants.SIX_YEARS),
    POURS_CUTS_WITH_SUPERVISION_AND_MASHES_OWN_FOOD("", Constants.FOUR_YEARS, Constants.SIX_YEARS),

    //5 year milestones
    WANTS_TO_PLEASE_FRIENDS("", Constants.FIVE_YEARS, Constants.SIX_YEARS),
    WANTS_TO_BE_LIKE_FRIENDS("", Constants.FIVE_YEARS, Constants.SIX_YEARS),
    MORE_LIKELY_TO_AGREE_WITH_RULES("", Constants.FIVE_YEARS, Constants.SIX_YEARS),
    LIKES_TO_SING_DANCE_AND_ACT("", Constants.FIVE_YEARS, Constants.SIX_YEARS),
    IS_AWARE_OF_GENDER("", Constants.FIVE_YEARS, Constants.SIX_YEARS),
    CAN_TELL_WHATS_REAL_AND_WHATS_MAKE_BELIEVE("", Constants.FIVE_YEARS, Constants.SIX_YEARS),
    SHOWS_MORE_INDEPENDENCE_FOR_EXAMPLE_MAY_VISIT_A_NEXT_DOOR_NEIGHBOR_BY_HIMSELF_ADULT_SUPERVISION_STILL_NEEDED("", Constants.FIVE_YEARS, Constants.SIX_YEARS),
    IS_SOMETIMES_DEMANDING_AND_SOMETIMES_VERY_COOPERATIVE("", Constants.FIVE_YEARS, Constants.SIX_YEARS),

    SPEAKS_VERY_CLEARLY("", Constants.FIVE_YEARS, Constants.SIX_YEARS),
    TELLS_A_SIMPLE_STORY_USING_FULL_SENTENCES("", Constants.FIVE_YEARS, Constants.SIX_YEARS),
    USES_FUTURE_TENSE_FOR_EXAMPLE_GRANDMA_WILL_BE_HERE("", Constants.FIVE_YEARS, Constants.SIX_YEARS),
    SAYS_NAME_AND_ADDRESS("", Constants.FIVE_YEARS, Constants.SIX_YEARS),

    COUNTS_TEN_OR_MORE_THINGS("", Constants.FIVE_YEARS, Constants.SIX_YEARS),
    CAN_DRAW_A_PERSON_WITH_AT_LEAST_SIX_BODY_PARTS("", Constants.FIVE_YEARS, Constants.SIX_YEARS),
    CAN_PRINT_SOME_LETTERS_OR_NUMBERS("", Constants.FIVE_YEARS, Constants.SIX_YEARS),
    COPIES_A_TRIANGLE_AND_OTHER_GEOMETRIC_SHAPES("", Constants.FIVE_YEARS, Constants.SIX_YEARS),
    KNOWS_ABOUT_THINGS_USED_EVERY_DAY_LIKE_MONEY_AND_FOOD("", Constants.FIVE_YEARS, Constants.SIX_YEARS),

    STANDS_ON_ONE_FOOT_FOR_TEN_SECONDS_OR_LONGER("", Constants.FIVE_YEARS, Constants.SIX_YEARS),
    HOPS_MAY_BE_ABLE_TO_SKIP("", Constants.FIVE_YEARS, Constants.SIX_YEARS),
    CAN_DO_A_SOMERSAULT("", Constants.FIVE_YEARS, Constants.SIX_YEARS),
    USES_A_FOR_AND_SPOON_AND_SOMETIMES_A_TABLE_KNIFE("", Constants.FIVE_YEARS, Constants.SIX_YEARS),
    CAN_USE_THE_TOILET_ON_HER_OWN("", Constants.FIVE_YEARS, Constants.SIX_YEARS),
    SWINGS_AND_CLIMBS("", Constants.FIVE_YEARS, Constants.SIX_YEARS);

    int appropriateAgeMinimum;
    int appropriateAgeMaximum;
    String descriptor;

    Milestone(String description, int minAge, int maxAge) {
        this.descriptor = description;
        this.appropriateAgeMinimum = minAge;
        this.appropriateAgeMaximum = maxAge;
    }

    Milestone() {
        this("no description available", 0, 0);
    }

}
