package amazingme.model;


import java.util.Collections;
import java.util.HashSet;
import java.util.Set;

import static amazingme.model.Milestone.HERSELF;

public enum Skill {

    SOCIAL_AND_EMOTIONAL(Milestone.BEGINS_TO_SMILE_AT_PEOPLE, Milestone.TRIES_TO_LOOK_AT_PARENT
    , Milestone.CAN_BRIEFLY_CALM,HERSELF , Milestone.SMILES_SPONTANEOUSLY_ESPECIALLY_AT_PEOPLE
            , Milestone.LIKES_TO_PLAY_WITH_PEOPLE_AND_MIGHT_CRY_WHEN_PLAYING_STOPS
            , Milestone.COPIES_SOME_MOVEMENTS_AND_FACIAL_EXPRESSIONS_LIKE_SMILING_OR_FROWNING
            , Milestone.KNOWS_FAMILIAR_FACES_AND_BEGINS_TO_KNOW_IF_SOMEONE_IS_A_STRANGER
            , Milestone.LIKES_TO_PLAY_WITH_OTHERS_ESPECIALLY_PARENTS
            , Milestone.RESPONDS_TO_OTHER_PEOPLES_EMOTIONS_AND_OFTEN_SEEMS_HAPPY
            , Milestone.LIKES_TO_LOOK_AT_SELF_IN_A_MIRROR
            , Milestone.MAY_BE_AFRAID_OF_STRANGERS
            , Milestone.MAY_BE_CLINGY_WITH_FAMILIAR_ADULTS
            , Milestone.HAS_FAVORITE_TOYS
            , Milestone.IS_SHY_OR_NERVOUS_WITH_STRANGERS
            , Milestone.CRIES_WHEN_MOM_OR_DAD_LEAVES
            , Milestone.HAS_FAVORITE_THINGS_AND_PEOPLE
            , Milestone.SHOWS_FEAR_IN_SOME_SITUATIONS
            , Milestone.HANDS_YOU_A_BOOK_WHEN_HE_WANTS_TO_HEAR_A_STORY
            , Milestone.REPEATS_SOUNDS_OR_ACTIONS_TO_GET_ATTENTION
            , Milestone.PUTS_OUT_ARM_OR_LEG_TO_HELP_WITH_DRESSING
            , Milestone.PLAYS_GAMES_SUCH_AS_PEEK_A_BOO_AND_PAT_A_CAKE
            , Milestone.LIKES_TO_HAND_THINGS_TO_OTHERS_AS_PLAY
            , Milestone.MAY_HAVE_TEMPER_TANTRUMS
            , Milestone.MAY_BE_AFRAID_OF_STRANGERS_TWO
            , Milestone.SHOWS_AFFECTION_TO_FAMILIAR_PEOPLE
            , Milestone.PLAYS_SIMPLE_PRETEND_SUCH_AS_FEEDING_A_DOLL
            , Milestone.MAY_CLING_TO_CAREGIVERS_IN_NEW_SITUATIONS
            , Milestone.POINTS_TO_SHOW_OTHERS_SOMETHING_INTERESTING
            , Milestone.EXPLORES_ALONE_BUT_WITH_PARENT_CLOSE_BY
            , Milestone.COPIES_OTHERS_ESPECIALLY_ADULTS_AND_OLDER_CHILDREN
            , Milestone.GETS_EXCITED_WHEN_WITH_OTHER_CHILDREN
            , Milestone.SHOWS_MORE_AND_MORE_INDEPENDENCE
            , Milestone.SHOWS_DEFIANT_BEHAVIOR_DOING_WHAT_HE_HAS_BEEN_TOLD_NOT_TO
            , Milestone.PLAYS_MAINLY_BESIDE_OTHER_CHILDREN_BUT_IS_BEGINNING_TO_INCLUDE_OTHER_CHILDREN_SUCH_AS_IN_CHASE_GAMES
            , Milestone.COPIES_ADULTS_AND_FRIENDS
            , Milestone.SHOWS_AFFECTION_FOR_FRIENDS_WITHOUT_PROMPTING
            , Milestone.TAKES_TURNS_IN_GAMES
            , Milestone.SHOWS_CONCERN_FOR_CRYING_FRIEND
            , Milestone.UNDERSTANDS_THE_IDEA_OF_MINE_AND_HIS_OR_HERS
            , Milestone.SHOWS_WIDE_RANGE_OF_EMOTIONS
            , Milestone.SEPARATES_EASILY_FROM_MOM_AND_DAD
            , Milestone.MAY_GET_UPSET_WITH_MAJOR_CHANGES_IN_ROUTINE
            , Milestone.DRESSES_AND_UNDRESSES_SELF
            , Milestone.ENJOYS_DOING_NEW_THINGS
            , Milestone.PLAYS_MOM_AND_DAD
            , Milestone.IS_MORE_AND_MORE_CREATIVE_WITH_MAKE_BELIEVE_PLAY
            , Milestone.WOULD_RATHER_PLAY_WITH_OTHER_CHILDREN_THAN_BY_HIMSELF
            , Milestone.COOPERATES_WITH_OTHER_CHILDREN
            , Milestone.OFTEN_CANT_TELL_WHATS_REAL_AND_WHATS_MAKE_BELIEVE
            , Milestone.TALKS_ABOUT_WHAT_SHE_LIKES_AND_WHAT_SHE_IS_INTERESTED_IN
            , Milestone.WANTS_TO_PLEASE_FRIENDS
            , Milestone.WANTS_TO_BE_LIKE_FRIENDS
            , Milestone.MORE_LIKELY_TO_AGREE_WITH_RULES
            , Milestone.LIKES_TO_SING_DANCE_AND_ACT
            , Milestone.IS_AWARE_OF_GENDER
            , Milestone.CAN_TELL_WHATS_REAL_AND_WHATS_MAKE_BELIEVE
            , Milestone.SHOWS_MORE_INDEPENDENCE_FOR_EXAMPLE_MAY_VISIT_A_NEXT_DOOR_NEIGHBOR_BY_HIMSELF_ADULT_SUPERVISION_STILL_NEEDED
            , Milestone.IS_SOMETIMES_DEMANDING_AND_SOMETIMES_VERY_COOPERATIVE
    ),
    LANGUAGE_AND_COMMUNICATION(Milestone.COOS_OR_MAKES_GURGLING_SOUNDS, Milestone.TURNS_HEAD_TOWARD_SOUNDS,
            Milestone.UNDERSTANDS_WORDS_LIKE_IN_ON_AND_UNDER),
    COGNITIVE(Milestone.BEGINS_TO_FOLLOW_THINGS_WITH_EYES, Milestone.CRIES_AND_FUSSES_IF_ACTIVITY_DOESNT_CHANGE),
    MOVEMENT_AND_PHYSICAL_DEVELOPMENT;

    Set<Milestone> relatedMilestones;

    Skill(Milestone... milestones) {
        this.relatedMilestones = new HashSet<>();
        Collections.addAll(relatedMilestones, milestones);
    }

}
